{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "minio.secretName" . }}
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  # rootUser: {{ .Values.rootUser | b64enc | quote }}
  # rootPassword: {{ .Values.rootPassword | b64enc | quote }}
  
  accessKey: {{ index (index .Values.svcaccts 0) "accessKey" | b64enc | quote }}
  secretKey: {{ index (index .Values.svcaccts 0) "secretKey" | b64enc | quote }}
  rootUser: {{ include "minio.root.username" . | b64enc | quote }}
  rootPassword: {{ include "minio.root.password" . | b64enc | quote }}
  endpoint: {{ include "minio.fullname" . | b64enc | quote }}
  {{- if .Values.etcd.clientCert }}
  etcd_client.crt: {{ .Values.etcd.clientCert | toString | b64enc | quote }}
  {{- end }}
  {{- if .Values.etcd.clientCertKey }}
  etcd_client.key: {{ .Values.etcd.clientCertKey | toString | b64enc | quote }}
  {{- end }}
{{- end }}
